### ISSUE TITLE
Quoted numerical tags

### ISSUE THREAD

**Issue by GingerAvalanche** [NiceneNerd/roead#10]
The following Python code illustrates that system.bchmres contains quoted integer keys that are actually integer strings.

The macro read_map seems to check if the key is quoted, and then if it's *not*, attempt to parse it as an integer. However, in practice, keys from system.bchmres that *are* quoted integers get parsed as integers, instead of as strings like they should be. I'm not entirely sure of the mechanics behind this, but this definitely seems like unintended behavior, just by reading the code.

I know that removing the integer parsing causes the quoted numbers to be read as strings, but I'm pretty sure it should also cause unquoted numbers to be read as strings, so I'm not sure of a good step forward, here.

```
>>> p = p / "Bootup.pack"
>>> p.exists()
True
>>> s = oead.Sarc(p.read_bytes())
>>> f = s.get_file("Chemical/system.bchmres")
>>> f
Sarc.File(Chemical/system.bchmres)
>>> f.data
<memory at 0x00000192B8FA4B80>
>>> pio = oead.aamp.ParameterIO.from_binary(f.data)
>>> for key in pio.lists["world"].objects.keys():
...   print(key.hash)
...
4108050209
2212294583
>>> 0 in pio.lists["world"].objects
False
>>> "0" in pio.lists["world"].objects
True
```

**Comment by NiceneNerd** [comment]
Between this and #9 it's striking me how dumb it was that I never added a comprehensive binary<->text roundtrip test.

**Comment by NiceneNerd** [comment]
So it turns out this one is because the flag marking a key as quoted in ryml was actually experimental and doesn't work. In oead there was a manual workaround that would technically be a no-no in Rust, but I'll probably have to go for it anyway.
