### ISSUE TITLE
bcett.byml map files Vector 0.0s inverted upon dump, causing crashes.

### ISSUE THREAD

**Issue by MaxLastBreath** [NiceneNerd/roead#7]
Talking primarily about TOTK, there's a rotational vectors that have rotation of -0.0 that is lost upon dumping to yaml, this causes the game to crash. I don't know rust otherwise I'd fix it myself, it shouldn't be a hard fix though. 

Example-> Rotation: [-0.0, 1.1, -0.0] end up looking like [0.0, 1.1, 0.0] which causes the game to crash, manually editing the file and adding the - fixes this issue.

Here's a file that is affected with over 4500 entries of this issue.
TOTK-> Banc\MainField\Sky\StartIslandMerge2_Dynamic.bcett.byml.zs

**Comment by ArchLeaders** [comment]
This is an issue with lexical:

https://github.com/Alexhuszagh/rust-lexical/issues/94

**Comment by MaxLastBreath** [comment]
Yeah me and archleaders were looking through it, he was partially able to fix it.
