### ISSUE TITLE
Oead Tag Support

### ISSUE THREAD

**Issue by GingerAvalanche** [NiceneNerd/roead#9]
I've been diving into updating Hyrule Builder to latest roead (for some reason, the current version breaks for me) and I've encountered a very interesting bug.

In BotW, there's a lot of situations (notably in AIProgram and ASList) where a value needs to be the string value `Null` - but it seems like roead's yaml parser reads `!str64 Null` as Scalar::Null, instead of Scalar::String("Null") like it should, notably ignoring the yaml tag.

Is there a performance or functionality reason for dropping support for the tags defined by oead?

EDIT: Actually, it seems like I just read the code wrong. Support wasn't dropped, this is just an accidental bug where the value is read and then coerced to Scalar::Null before control flow point where the tag being TagBasedType::Str actually matters.

Given that the only time that TagBasedType::Str is passed to yaml::parse_scalar() is when it absolutely must be a string (`!str32`, `!str64`, and `!str256`), I'm going to PR a fix where TagBasedType::Str comes in before other checks, because, presumably, if someone puts a string tag there, they really do want it to be a string.

**Comment by NiceneNerd** [comment]
I actually ran into this issue myself not long ago and was working on fixing it but ended up getting distracted. I'll double check if I have the fixed code sitting around.

**Comment by NiceneNerd** [comment]
Oh, actually, what I'm remembering is when I fixed it to recognize nulls as strings, but it treats them all as blank strings rather than the string `Null`. This seems to be in part an ambiguity with the YAML spec itself, as it officially recognizes reserved words like `null` no matter what the casing.

I guess since AAMP doesn't use "real" null values then as long as we end up with it emitting `null` we should be fine to treat them all as the literal string.

**Comment by GingerAvalanche** [comment]
I ended up trying to fix it by rewriting it, because the parse_scalar implementation seems to use the tag type as a suggestion, which... if a tag is specified, shouldn't that be definitive? Unless I'm misunderstanding, a tag type should only be given to parse_scalar if there's an explicit tag to coerce to that type.

I ran into more problems with using tag types as definitive, though, where it decided that a string value was supposed to be parsed as an integer when reading a text file as byml, though I have no idea why that would be the case, as there are no tags in byml that I've ever seen.

**Comment by GingerAvalanche** [comment]
My fix might assume that Null nodes are never actually used. It might be that the writer emits `Null` for null nodes, and so any game that uses them would have a problem.

This *would* cause round trip errors if it were the case, but I don't have a byml with a null node, and, honestly, I'm not really sure how to make one to test.
